version: '3.1'

services:
  phalcon4:
    container_name: phalcon4
    image: phalcon4
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:80
      - 80:80
    volumes:
      - /Users/secgin/ww7:/var/www/html/

networks:
  my_network:
    external: true