services:

  php:
    container_name: php83-apache
    image: php83-apache
    build:
      dockerfile: Dockerfile
    ports:
      - 8070:80
    volumes:
      - /Users/secgin/www:/var/www/html/
    networks:
      - my_network

networks:
  my_network:
    external: true