services:

  phalcon5:
    container_name: phalcon5
    image: phalcon5
    build:
      dockerfile: Dockerfile
    ports:
      - 8075:80
    volumes:
      - d:\www:/var/www/html/
    networks:
      - my_network

networks:
  my_network:
    external: true